### ISSUE TITLE
CO_E_SERVER_EXEC_FAILURE on non-admin impersonation

### ISSUE THREAD

**Issue by forderud** [forderud/RunInSandbox#1]
Attempting to run "`RunInSandbox.exe TestControl.TestControl <username> <password>`" works fine when impersonating an admin user. However, it fails with with: `hr = 0x80080005 : Server execution failed` when attempting to impersonate a non-admin user.

The following event is also logged in the Windows **System** event log:
```
The server {F0DFBE77-1697-428E-A895-EFEE202B9333} did not register with DCOM within the required timeout.
```

### Precondition:
Enable `TestControl Object` DCOM local "launch" and "activation" permissions for the impersonated user. Failure to do so will lead to CoCreateInstance failing with `E_ACCESSDENIED`.
![image](https://user-images.githubusercontent.com/2671400/58557077-cad30400-821d-11e9-8084-52cb09b65430.png)
This can also be enabled globally through the default DCOM launch & activation permissions:
![image](https://user-images.githubusercontent.com/2671400/58563172-e8f33100-822a-11e9-9fd2-f392acbfdf8d.png)

### Steps to reproduce
1. Build RunInSandbox & TestControl projects.
2. Create a new user account that is only member of the "Users" group.
3. Enable local DCOM "launch" and "activation" for the new user.
4. Verify that "`RunInSandbox.exe TestControl.TestControl <username> <password>`" fails with CO_E_SERVER_EXEC_FAILURE
5. Add user to "Administrators" group
6. Verify that "`RunInSandbox.exe TestControl.TestControl <username> <password>`" now succeed.

**Comment by forderud** [comment]
https://docs.microsoft.com/en-us/windows/desktop/api/combaseapi/nf-combaseapi-coregisterclassobject

**Comment by PFFyodor** [comment]
Hi friend, i on this steps too, its real trouble to make ActiveX to work on Windows10 + x64 mode with EPM.
When you run "as Administrator" - its work because EPM mode is auto-disabling.

i working on it, if you found something - tell please :)

**Comment by forderud** [comment]
Closing, since this problem is not longer relevant after managing to get AppContainer sandboxing up&running.

**Comment by forderud** [comment]
Notes:
* Need to grant the "RunAs" user filesystem permissions to the COM server.
* ..

**Comment by forderud** [comment]
Problem appear to have disappeared when using the new `ComRunAs` tool.
