### ISSUE TITLE
Electron apps always fails to launch with anything less than Medium IL

### ISSUE THREAD

**Issue by rawlife56** [forderud/RunInSandbox#5]
Hey, thanks for this project and helping me to get started with AppContainers. Few system apps work fine. I've been trying to containerize an electron app but almost all of them fail to launch in less than medium integrity level even with broad set of permissions. 

Lets take Signal messenger as an example here. Can you please have a look and let me know if I'm missing some key minor aspects. It would be very helpful if I can get a demo electron app working inside the AppContainer.

**Comment by forderud** [comment]
Thank you for taking an interest in this project.

I've never worked with Electron myself, so it's difficult to give any concrete advise. However, I would recommend you to use [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to monitor the sandboxed process for failing file, registry and/or network access. This will often reveal some clues about the reason for the launch failure.

**Comment by rawlife56** [comment]
Yeah, I've tried to do that way but process monitor didn't show anything related to this program I was trying. Anyways, I will look into it once again and report back if I'm able to get it working. 👍

**Comment by forderud** [comment]
Closing issue, since it's most likely related to Electron and not to this project.
